# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import fineuploader.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fineuploader', '0002_auto_20180419_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('formid', models.CharField(max_length=128)),
                ('field_name', models.CharField(blank=True, max_length=256, null=True)),
                ('file_obj', models.FileField(max_length=255, upload_to=fineuploader.models.upload_path, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='original filename')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'temporary upload',
                'verbose_name_plural': 'temporary uploads',
            },
        ),
        migrations.DeleteModel(
            name='Temporary',
        ),
        migrations.AlterIndexTogether(
            name='upload',
            index_together=set([('formid', 'field_name')]),
        ),
    ]
